**Trabalho de Deep Learning**



In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
import pathlib

import matplotlib.pyplot as plt
import seaborn as sns

print(tf.__version__)

2.3.0


In [3]:
link = "https://raw.githubusercontent.com/rmicheldev/datasets/main/MoviesOnStreamingPlatforms_updated.csv"

# Carrega o arquivo do github
rawDf = pd.read_csv(link)

In [4]:
rawDf.head(10)

Unnamed: 0  ID  ...                                     Language  Runtime
0           0   1  ...                      English,Japanese,French    148.0
1           1   2  ...                                      English    136.0
2           2   3  ...                                      English    149.0
3           3   4  ...                                      English    116.0
4           4   5  ...                                      Italian    161.0
5           5   6  ...                              English,Spanish    117.0
6           6   7  ...                       English,German,Russian    150.0
7           7   8  ...                English,German,French,Italian    165.0
8           8   9  ...  English,German,Hebrew,Spanish,Arabic,Nepali    115.0
9           9  10  ...                English,German,French,Italian    153.0

[10 rows x 17 columns]

In [5]:
#Mostra os tipos de dados
rawDf.dtypes

Unnamed: 0           int64
ID                   int64
Title               object
Year                 int64
Age                 object
IMDb               float64
Rotten Tomatoes     object
Netflix              int64
Hulu                 int64
Prime Video          int64
Disney+              int64
Type                 int64
Directors           object
Genres              object
Country             object
Language            object
Runtime            float64
dtype: object

* Unnamed: 0           int64   Numerical
* ID                   int64   Numerical 
* Title               object   ????
* Year                 int64   Numerical 
* Age                 object   Categorical
* IMDb               float64   Numerical
* Rotten Tomatoes     object   Numerical
* Netflix              int64   Categorical
* Hulu                 int64   Categorical
* Prime Video          int64   Categorical
* Disney+              int64   Categorical
* Type                 int64   Categorical
* Directors           object   Categorical
* Genres              object   Categorical 
* Country             object   Categorical
* Language            object   Categorical 
* Runtime            float64   Numerical

In [6]:
# Remove a primeira coluna (indice 0) que não possui valor e a coluna Type e a nota no Rotten Tomatoes 
explDf = rawDf.drop(rawDf.columns[[0]], axis=1).drop(['Type','Rotten Tomatoes'], axis=1)
explDf.head(10)

ID  ... Runtime
0   1  ...   148.0
1   2  ...   136.0
2   3  ...   149.0
3   4  ...   116.0
4   5  ...   161.0
5   6  ...   117.0
6   7  ...   150.0
7   8  ...   165.0
8   9  ...   115.0
9  10  ...   153.0

[10 rows x 14 columns]

In [7]:
# Dropa todas as linhas que tem colunas faltando informação 
explDf = explDf.dropna()
display(explDf)

ID                            Title  ...                 Language Runtime
0          1                        Inception  ...  English,Japanese,French   148.0
1          2                       The Matrix  ...                  English   136.0
2          3           Avengers: Infinity War  ...                  English   149.0
3          4               Back to the Future  ...                  English   116.0
4          5   The Good, the Bad and the Ugly  ...                  Italian   161.0
...      ...                              ...  ...                      ...     ...
16726  16727     Richie Rich's Christmas Wish  ...                  English    84.0
16727  16728  The Jungle Book: Mowgli's Story  ...                  English    77.0
16737  16738                  The Bears and I  ...                  English    89.0
16738  16739     Whispers: An Elephant's Tale  ...                  English    72.0
16740  16741                   The Poof Point  ...                  English    90.0

[7046 rows x 14 columns]

In [8]:
rawDf.head(10)

Unnamed: 0  ID  ...                                     Language  Runtime
0           0   1  ...                      English,Japanese,French    148.0
1           1   2  ...                                      English    136.0
2           2   3  ...                                      English    149.0
3           3   4  ...                                      English    116.0
4           4   5  ...                                      Italian    161.0
5           5   6  ...                              English,Spanish    117.0
6           6   7  ...                       English,German,Russian    150.0
7           7   8  ...                English,German,French,Italian    165.0
8           8   9  ...  English,German,Hebrew,Spanish,Arabic,Nepali    115.0
9           9  10  ...                English,German,French,Italian    153.0

[10 rows x 17 columns]

In [9]:
explDf.head(10)

ID  ... Runtime
0   1  ...   148.0
1   2  ...   136.0
2   3  ...   149.0
3   4  ...   116.0
4   5  ...   161.0
5   6  ...   117.0
6   7  ...   150.0
7   8  ...   165.0
8   9  ...   115.0
9  10  ...   153.0

[10 rows x 14 columns]

In [10]:
#renomeando colunas
colsRen = {'ID':'id',
        'Title':'title',
        'Year':'year',
        'Age':'age',
        'IMDb':'imdb',        
        'Netflix':'netflix',
        'Hulu':'hulu',
        'Prime Video':'prime',
        'Disney+':'disney',        
        'Directors':'directors',
        'Genres':'genres',
        'Country':'country',
        'Language':'language',
        'Runtime':'runtime'
        }


explDf = explDf.rename(columns = colsRen, inplace = False)
explDf.dtypes

id             int64
title         object
year           int64
age           object
imdb         float64
netflix        int64
hulu           int64
prime          int64
disney         int64
directors     object
genres        object
country       object
language      object
runtime      float64
dtype: object

In [11]:
#Dividindo os dados para treino e teste (validação)
testeDf = explDf.sample(frac=0.2, random_state=42)
treinoDf = explDf.drop(testeDf.index)

print("%d amostras para treino e %d para teste" % (len(treinoDf),len(testeDf)))

5637 amostras para treino e 1409 para teste


In [12]:
def dataframe_to_dataset(dataframe):
    dataframe = dataframe.copy()
    labels = dataframe.pop("imdb")
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    ds = ds.shuffle(buffer_size=len(dataframe))
    return ds

In [13]:
treinoDs = dataframe_to_dataset(treinoDf)
testeDs = dataframe_to_dataset(testeDf)

In [14]:
treinoDs.element_spec

({'age': TensorSpec(shape=(), dtype=tf.string, name=None),
  'country': TensorSpec(shape=(), dtype=tf.string, name=None),
  'directors': TensorSpec(shape=(), dtype=tf.string, name=None),
  'disney': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'genres': TensorSpec(shape=(), dtype=tf.string, name=None),
  'hulu': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'id': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'language': TensorSpec(shape=(), dtype=tf.string, name=None),
  'netflix': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'prime': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'runtime': TensorSpec(shape=(), dtype=tf.float64, name=None),
  'title': TensorSpec(shape=(), dtype=tf.string, name=None),
  'year': TensorSpec(shape=(), dtype=tf.int64, name=None)},
 TensorSpec(shape=(), dtype=tf.float64, name=None))

In [15]:
testeDs.element_spec

({'age': TensorSpec(shape=(), dtype=tf.string, name=None),
  'country': TensorSpec(shape=(), dtype=tf.string, name=None),
  'directors': TensorSpec(shape=(), dtype=tf.string, name=None),
  'disney': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'genres': TensorSpec(shape=(), dtype=tf.string, name=None),
  'hulu': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'id': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'language': TensorSpec(shape=(), dtype=tf.string, name=None),
  'netflix': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'prime': TensorSpec(shape=(), dtype=tf.int64, name=None),
  'runtime': TensorSpec(shape=(), dtype=tf.float64, name=None),
  'title': TensorSpec(shape=(), dtype=tf.string, name=None),
  'year': TensorSpec(shape=(), dtype=tf.int64, name=None)},
 TensorSpec(shape=(), dtype=tf.float64, name=None))

In [16]:
list(treinoDs.as_numpy_iterator())


[({'age': b'7+',
   'country': b'United Kingdom',
   'directors': b'David Greene',
   'disney': 0,
   'genres': b'Drama',
   'hulu': 0,
   'id': 10298,
   'language': b'English',
   'netflix': 0,
   'prime': 1,
   'runtime': 104.0,
   'title': b'Hard Country',
   'year': 1981},
  5.9),
 ({'age': b'18+',
   'country': b'United States',
   'directors': b'Ana Lily Amirpour',
   'disney': 0,
   'genres': b'Drama,Horror,Romance,Sci-Fi',
   'hulu': 0,
   'id': 1108,
   'language': b'English',
   'netflix': 1,
   'prime': 0,
   'runtime': 118.0,
   'title': b'The Bad Batch',
   'year': 2017},
  5.3),
 ({'age': b'18+',
   'country': b'United States',
   'directors': b'John Erman',
   'disney': 0,
   'genres': b'Crime,Drama',
   'hulu': 0,
   'id': 8942,
   'language': b'English',
   'netflix': 0,
   'prime': 1,
   'runtime': 93.0,
   'title': b'Carolina Skeletons',
   'year': 1991},
  6.2),
 ({'age': b'18+',
   'country': b'United Kingdom,United States,Mexico',
   'directors': b'John Schlesing

In [17]:
for x, y in treinoDs.take(2):
    print("Input:", x)
    print("Target:", y)

Input: {'id': <tf.Tensor: shape=(), dtype=int64, numpy=5011>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Intact'>, 'year': <tf.Tensor: shape=(), dtype=int64, numpy=2001>, 'age': <tf.Tensor: shape=(), dtype=string, numpy=b'18+'>, 'netflix': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'hulu': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'prime': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'disney': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'directors': <tf.Tensor: shape=(), dtype=string, numpy=b'Juan Carlos Fresnadillo'>, 'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Drama,Fantasy,Romance,Thriller'>, 'country': <tf.Tensor: shape=(), dtype=string, numpy=b'Spain'>, 'language': <tf.Tensor: shape=(), dtype=string, numpy=b'Spanish,English,French'>, 'runtime': <tf.Tensor: shape=(), dtype=float64, numpy=108.0>}
Target: tf.Tensor(6.9, shape=(), dtype=float64)
Input: {'id': <tf.Tensor: shape=(), dtype=int64, numpy=944>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'B

In [18]:
treinoDs = treinoDs.batch(32)
testeDs = testeDs.batch(32)

In [19]:
list(treinoDs.as_numpy_iterator())

[({'age': array([b'all', b'18+', b'all', b'7+', b'18+', b'7+', b'18+', b'13+',
          b'7+', b'7+', b'all', b'13+', b'18+', b'18+', b'18+', b'18+',
          b'18+', b'18+', b'13+', b'13+', b'7+', b'7+', b'7+', b'18+',
          b'18+', b'18+', b'7+', b'18+', b'18+', b'all', b'7+', b'7+'],
         dtype=object),
   'country': array([b'India', b'United States', b'United States', b'United States',
          b'Canada', b'United States', b'United States', b'United States',
          b'United States', b'Canada', b'United States', b'United States',
          b'South Korea', b'United States',
          b'United Kingdom,France,Germany,Spain,South Africa',
          b'United States', b'United States', b'Taiwan,Hong Kong',
          b'United States', b'South Korea', b'United States', b'Japan',
          b'United Kingdom,United States', b'United States', b'Canada',
          b'Italy', b'United States', b'United Kingdom,Germany', b'Canada',
          b'Sweden,Netherlands,Italy', b'United State

In [ ]:
sns.pairplot(treinoDf[["year","age","imdb","netflix","hulu","prime","disney","directors","genres","country","language","runtime"]], diag_kind="kde")



In [ ]:
# código retirado de https://keras.io/examples/structured_data/structured_data_classification_from_scratch/
from tensorflow.keras.layers.experimental.preprocessing import Normalization
from tensorflow.keras.layers.experimental.preprocessing import CategoryEncoding
from tensorflow.keras.layers.experimental.preprocessing import StringLookup


def encode_numerical_feature(feature, name, dataset):
    # Create a Normalization layer for our feature
    normalizer = Normalization()

    # Prepare a Dataset that only yields our feature
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the statistics of the data
    normalizer.adapt(feature_ds)

    # Normalize the input feature
    encoded_feature = normalizer(feature)
    return encoded_feature


def encode_string_categorical_feature(feature, name, dataset):
    # Create a StringLookup layer which will turn strings into integer indices
    index = StringLookup()

    # Prepare a Dataset that only yields our feature
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the set of possible string values and assign them a fixed integer index
    index.adapt(feature_ds)

    # Turn the string input into integer indices
    encoded_feature = index(feature)

    # Create a CategoryEncoding for our integer indices
    encoder = CategoryEncoding(output_mode="binary")

    # Prepare a dataset of indices
    feature_ds = feature_ds.map(index)

    # Learn the space of possible indices
    encoder.adapt(feature_ds)

    # Apply one-hot encoding to our indices
    encoded_feature = encoder(encoded_feature)
    return encoded_feature


def encode_integer_categorical_feature(feature, name, dataset):
    # Create a CategoryEncoding for our integer indices
    encoder = CategoryEncoding(output_mode="binary")

    # Prepare a Dataset that only yields our feature
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the space of possible indices
    encoder.adapt(feature_ds)

    # Apply one-hot encoding to our indices
    encoded_feature = encoder(feature)
    return encoded_feature


In [ ]:
shp = (1,)

year =  keras.Input(shape=shp,name="year", dtype="int64") 
netflix =  keras.Input(shape=shp,name="netflix", dtype="int64")
hulu =  keras.Input(shape=shp,name="hulu", dtype="int64") 
prime =  keras.Input(shape=shp,name="prime", dtype="int64")
disney =  keras.Input(shape=shp,name="disney", dtype="int64")

runtime = keras.Input(shape=shp,name="runtime")

age = keras.Input(shape=shp,name="age", dtype="string")
directors = keras.Input(shape=shp,name="directors", dtype="string")
genres = keras.Input(shape=shp,name="genres", dtype="string")
country = keras.Input(shape=shp,name="country", dtype="string")
language = keras.Input(shape=shp,name="language", dtype="string")

In [ ]:
all_inputs = [
year,
netflix,
hulu,
prime,
disney,
runtime,
age,
directors,
genres,
country,
language
]

In [ ]:
print(all_inputs)

In [ ]:
year_encoded = encode_integer_categorical_feature(year, "year", treinoDs)
netflix_encoded = encode_integer_categorical_feature(netflix, "netflix", treinoDs)
hulu_encoded = encode_integer_categorical_feature(hulu, "hulu", treinoDs)
prime_encoded = encode_integer_categorical_feature(prime, "prime", treinoDs)
disney_encoded = encode_integer_categorical_feature(disney, "disney", treinoDs)

runtime_encoded = encode_numerical_feature(runtime, "runtime", treinoDs)

age_encoded = encode_string_categorical_feature(age, "age", treinoDs)
directors_encoded = encode_string_categorical_feature(directors, "directors", treinoDs)
genres_encoded = encode_string_categorical_feature(genres, "genres", treinoDs)
country_encoded = encode_string_categorical_feature(country, "country", treinoDs)
language_encoded = encode_string_categorical_feature(language, "language", treinoDs)

In [ ]:
all_features = layers.concatenate(
    [
     year_encoded,
     netflix_encoded,
     hulu_encoded,
     prime_encoded,
     disney_encoded,

     runtime_encoded,

     age_encoded,
     directors_encoded,
     genres_encoded,
     country_encoded,
     language_encoded   
    ]
)

In [ ]:
all_features

In [ ]:
#x = layers.Dense(32, activation="relu")(all_features)
#x = layers.Dropout(0.5)(x)
#output = layers.Dense(1, activation="sigmoid")(x)
#model = keras.Model(all_inputs, output)
#model.compile("adam", "binary_crossentropy", metrics=["accuracy"])


In [ ]:
x = layers.Dense(32, activation="relu")(all_features)
x = layers.Flatten()(x)
x = layers.Dropout(0.5)(x)
output = layers.Dense(1, activation="linear")(x)
model = keras.Model(all_inputs, output)
model.compile(optimizer="adam", loss="mse", metrics=['mse','mae'])

In [ ]:
model.summary()

In [ ]:
keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

In [ ]:
model.fit(treinoDs, epochs=10, validation_data=testeDs)

In [ ]:
# Testando com o filme Inception
sampleRec = {
    "year": 2010,
    "age": "13+",
    "netflix": 1,
    "hulu": 0,
    "prime": 0,
    "disney": 0,
    "directors": "Christopher Nolan",
    "genres": "Action,Adventure,Sci-Fi,Thriller",
    "country": "United States,United Kingdom",
    "language": "English,Japanese,French",
    "runtime": 148.0
}


#Testando com o filme Furie 
sampleNotRec = {
    "year": 2019,
    "age": "18+",
    "netflix": 1,
    "hulu": 0,
    "prime": 0,
    "disney": 0,
    "directors": "David Ayer",
    "genres": "Action,Drama,War",
    "country": "United States,China,United Kingdom",
    "language": "English,German",
    "runtime": 134.0
}

In [ ]:
input_dictRec = {name: tf.convert_to_tensor([value]) for name, value in sampleRec.items()}
predictionsRec = model.predict(input_dictRec)

In [ ]:
print(
    "A nota predita para este filme é %.1f" % (predictionsRec[0][0])
)

In [ ]:
input_dictNotRec = {name: tf.convert_to_tensor([value]) for name, value in sampleNotRec.items()}
predictionsNotRec = model.predict(input_dictNotRec)

In [ ]:
print(
    "A nota predita para este filme é %.1f" % (predictionsNotRec[0][0])
)